/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuela;//Parte grafica Estudiante

import Especialidad.NewJFrameEspecialidad;
import Estudiante.Estudiante;
import Horario.NewJFrameHorario;
import Materias.NewJFrameMaterias;
import Matricula.NewJFrameMatricula;
import Precios.NewJFramePrecios;
import Profesores.NewJFrameProfesores;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author treznor
 */
public class Pantalla_Principal extends javax.swing.JFrame {

//.conexión_postgres CP;
    public Pantalla_Principal() {

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSalir = new javax.swing.JButton();
        jBtnEstudiante = new javax.swing.JButton();
        jBtnEspecialidad = new javax.swing.JButton();
        jBtnProfesores = new javax.swing.JButton();
        jBtnMaterias = new javax.swing.JButton();
        jBtnPrecios = new javax.swing.JButton();
        jBtnHorarios = new javax.swing.JButton();
        jBtnMatricula = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnEstudiante.setText("Estudiante");
        jBtnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEstudianteActionPerformed(evt);
            }
        });

        jBtnEspecialidad.setText("Especialidad");
        jBtnEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEspecialidadActionPerformed(evt);
            }
        });

        jBtnProfesores.setText("Profesores");
        jBtnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProfesoresActionPerformed(evt);
            }
        });

        jBtnMaterias.setText("Materias");
        jBtnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMateriasActionPerformed(evt);
            }
        });

        jBtnPrecios.setText("Precios");
        jBtnPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPreciosActionPerformed(evt);
            }
        });

        jBtnHorarios.setText("Horarios");
        jBtnHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHorariosActionPerformed(evt);
            }
        });

        jBtnMatricula.setText("Matricula");
        jBtnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMatriculaActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPrecios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 289, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jBtnEstudiante)
                .addGap(7, 7, 7)
                .addComponent(jBtnProfesores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEspecialidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPrecios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnHorarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jBtnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEstudianteActionPerformed
        // TODO add your handling code here:
        Estudiante E = null;
        try {
            E = new Estudiante();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        E.setVisible(true);


    }//GEN-LAST:event_jBtnEstudianteActionPerformed

    private void jBtnEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEspecialidadActionPerformed
        // TODO add your handling code here:
        NewJFrameEspecialidad E = null;
        try {
            E = new NewJFrameEspecialidad();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        E.setVisible(true);
    }//GEN-LAST:event_jBtnEspecialidadActionPerformed

    private void jBtnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProfesoresActionPerformed
        // TODO add your handling code here:
        NewJFrameProfesores P = null;
        try {
            P = new NewJFrameProfesores();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        P.setVisible(true);


    }//GEN-LAST:event_jBtnProfesoresActionPerformed

    private void jBtnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMateriasActionPerformed
        // TODO add your handling code here:

        NewJFrameMaterias M = null;
        try {
            M = new NewJFrameMaterias();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        M.setVisible(true);


    }//GEN-LAST:event_jBtnMateriasActionPerformed

    private void jBtnPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPreciosActionPerformed
        // TODO add your handling code here:

        NewJFramePrecios Pr = null;
        try {
            Pr = new NewJFramePrecios();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Pr.setVisible(true);


    }//GEN-LAST:event_jBtnPreciosActionPerformed

    private void jBtnHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHorariosActionPerformed
        // TODO add your handling code here:

        NewJFrameHorario H = null;
        try {
            H = new NewJFrameHorario();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        H.setVisible(true);


    }//GEN-LAST:event_jBtnHorariosActionPerformed

    private void jBtnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMatriculaActionPerformed
        // TODO add your handling code here:
        
        NewJFrameMatricula M = null;
        try {
            M = new NewJFrameMatricula();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        M.setVisible(true);

    }//GEN-LAST:event_jBtnMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEspecialidad;
    private javax.swing.JButton jBtnEstudiante;
    private javax.swing.JButton jBtnHorarios;
    private javax.swing.JButton jBtnMaterias;
    private javax.swing.JButton jBtnMatricula;
    private javax.swing.JButton jBtnPrecios;
    private javax.swing.JButton jBtnProfesores;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
